const fs=require('fs');const edit=(p,fn)=>fs.writeFileSync(p,fn(fs.readFileSync(p,'utf8')));
edit('app/layout.tsx',s=>s.replace('import type { Metadata }','import { getI18n } from "@/lib/i18n/server";\nimport { LocaleProvider } from "@/context/LocaleContext";\nimport type { Metadata }').replace(/export const metadata: Metadata = \{[\s\S]*?\};/,'export async function generateMetadata(): Promise<Metadata> { const {t}=await getI18n(); return {title:t("brand.name"),description:t("brand.description")}; }').replace('export default function RootLayout','export default async function RootLayout').replace('  return (','  const {locale,dir,t}=await getI18n();\n  return (').replace('lang="en"','lang={locale}\n      dir={dir}').replace('<AuthProvider>','<LocaleProvider locale={locale}><AuthProvider>').replace('</AuthProvider>','</AuthProvider></LocaleProvider>').replace('Skip to content','{t("common.skip")}'));
edit('components/AppHeader.tsx',s=>s.replace('t, locale, dir,','t, locale, dir, setLocale, pending,').replace('<Button\n            variant="outline"','<Button variant="outline" aria-label={t("nav.language")} isDisabled={pending} onPress={() => setLocale(locale === "ar" ? "en" : "ar")} className="ms-auto shrink-0 px-3" lang={locale === "ar" ? "en" : "ar"}>{locale === "ar" ? t("nav.english") : t("nav.arabic")}</Button>\n          <Button\n            variant="outline"').replace('<Sheet isOpen={open}','<Sheet side={dir === "rtl" ? "left" : "right"} isOpen={open}').replaceAll('lg:flex','xl:flex').replaceAll('lg:hidden','xl:hidden').replace('flex shrink-0 items-center gap-3','flex min-w-0 items-center gap-2 sm:gap-3').replace('text-base font-bold leading-tight','text-sm sm:text-base font-bold leading-tight'));
edit('components/ReportTypeBadge.tsx',s=>'"use client";\nimport { useI18n } from "@/context/LocaleContext";\n'+s.replace('  const Icon','  const {t}=useI18n();\n  const Icon').replace('{type}','{t(type === "Lost" ? "report.lost" : "report.found")}'));
edit('components/ReportCard.tsx',s=>'"use client";\nimport { useI18n } from "@/context/LocaleContext";\n'+s.replace('  return (','  const {date,college}=useI18n();\n  return (').replace(/\{new Date\(post.createdAt\).toLocaleDateString\("en-GB", \{[\s\S]*?\}\)\}/,'{date(post.createdAt)}').replace('{post.collegeName}','{college(post.collegeName)}').replace('<h3 className=','<h3 dir="auto" className=').replace('<p className="mb-6','<p dir="auto" className="mb-6'));
edit('components/StatCard.tsx',s=>'"use client";\nimport { useI18n } from "@/context/LocaleContext";\n'+s.replace('import { LucideIcon } from "lucide-react";','import {Search, HandHeart, ClipboardList, MapPin, Users} from "lucide-react";\nconst icons={Search,HandHeart,ClipboardList,MapPin,Users};').replace('icon: Icon,','icon,').replace('icon: LucideIcon;','icon: keyof typeof icons;').replaceAll('navy','brand').replace('  return (','  const {number,translateMessage}=useI18n();\n  const Icon=icons[icon];\n  return (').replace('{label}','{translateMessage(label)}').replace('{description}','{translateMessage(description)}').replace('{value.toLocaleString()}','{number(value)}'));
for(const p of ['app/page.tsx','app/admin/page.tsx'])edit(p,s=>s.replace(/icon=\{(ClipboardList|Search|HandHeart|MapPin|Users)\}/g,'icon="$1"'));
edit('components/BrowseReports.tsx',s=>s.replace('{type} items','{t(type === "Lost" ? "nav.lost" : "nav.found")}'));
edit('components/SearchPanel.tsx',s=>s.replace('{c.name}','{college(c.name)}'));
edit('components/FilterBar.tsx',s=>s.replace('label: "Lost"','label: t("report.lost")').replace('label: "Found"','label: t("report.found")').replace('{count} {count === 1 ? "report" : "reports"}','{reportCount(count)}'));
edit('app/posts/[id]/page.tsx',s=>s.replace(/  const createdDate[\s\S]*?\n  return \(/,'  const formattedDate = date(post.createdAt, true);\n\n  return (').replace('Back to {post.type.toLowerCase()} items','{t(post.type === "Lost" ? "report.backLost" : "report.backFound")}').replace('Report #{post.id}','{t("report.number",{id:post.id})}').replace('{post.collegeName}','{college(post.collegeName)}').replace('{post.contactNumber}','<bdi dir="ltr">{post.contactNumber}</bdi>').replace('{t("report.reported")}<time','{t("report.reported")} <time').replace('<h1 className=','<h1 dir="auto" className=').replace('<p className="whitespace-pre-wrap','<p dir="auto" className="whitespace-pre-wrap'));
for(const p of ['app/my-posts/page.tsx','app/admin/page.tsx'])edit(p,s=>s.replace(/\{new Date\(post.createdAt\).toLocaleDateString\([^)]*\)\}/g,'{date(post.createdAt)}').replace('{post.collegeName}','{college(post.collegeName)}').replace('aria-label={`Delete ${post.title}`}','aria-label={t("admin.deleteLabel", {title:post.title})}').replace('{u.email}','<bdi dir="ltr">{u.email}</bdi>').replace('{u.id}','<bdi dir="ltr">{u.id}</bdi>'));
// Keep identifiers in props intact while isolating displayed values.
edit('app/admin/page.tsx',s=>s.replace('id=<bdi dir="ltr">{u.id}</bdi> key=<bdi dir="ltr">{u.id}</bdi>','id={u.id} key={u.id}').replace('<Sidebar className=','<Sidebar side={dir === "rtl" ? "right" : "left"} dir={dir} className='));
edit('components/PostForm.tsx',s=>s.replace('{c.name}','{college(c.name)}').replace('{values.title.length}/100','{t("form.counter",{count:values.title.length,max:100})}').replace('{values.description.length}/1000','{t("form.counter",{count:values.description.length,max:1000})}').replace('id="contactNumber"','id="contactNumber"\n              dir="ltr"').replace('id="title"','id="title"\n              dir="auto"').replace('id="description"','id="description"\n              dir="auto"'));
// Translate server errors by status; do not modify the API error object or payload.
for(const p of ['components/PostForm.tsx','app/login/page.tsx','app/register/page.tsx','app/my-posts/page.tsx','app/admin/page.tsx'])edit(p,s=>s.replace(/err instanceof ApiError\s*\? err.message\s*:\s*t\("([^"]+)"\)/g,'errorText(err, "$1")').replace('<AlertDescription>{error}</AlertDescription>','<AlertDescription>{translateMessage(error)}</AlertDescription>'));
edit('components/ErrorState.tsx',s=>s.replace('{message}','{translateMessage(message)}'));
edit('app/not-found.tsx',s=>s.replace(/<main\b/g,'<div').replaceAll('</main>','</div>'));
// Translate the loading announcements used by protected pages too.
edit('components/LoadingState.tsx',s=>'"use client";\nimport { useI18n } from "@/context/LocaleContext";\n'+s.replace('  if (type','  const {t}=useI18n();\n  if (type').replace(/<div className="(space-y-4|grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4|space-y-2)">/g,'<div role="status" aria-label={t("common.loading")} className="$1">'));
fs.writeFileSync('components/Spinner.tsx','"use client";\nimport {useI18n} from "@/context/LocaleContext";\nexport default function Spinner(){const {t}=useI18n();return <div role="status" aria-label={t("common.loading")} className="flex justify-center py-12"><div aria-hidden className="size-6 rounded-full border-2 border-border border-t-primary animate-spin"/></div>;}\n');
// Logical properties mirror layouts without changing their visual structure.
for(const d of ['app','components'])for(const p of fs.readdirSync(d,{recursive:true}).filter(p=>p.endsWith('.tsx')).map(p=>d+'/'+p)){edit(p,s=>s.replace(/\bml-/g,'ms-').replace(/\bmr-/g,'me-').replace(/\bpl-/g,'ps-').replace(/\bpr-/g,'pe-').replace(/\btext-left\b/g,'text-start').replace(/\btext-right\b/g,'text-end').replace(/(<Arrow(?:Left|Right|UpRight)\b[^>]*className=")/g,'$1rtl:-scale-x-100 ').replaceAll('text-slate-200','text-primary-foreground/85').replaceAll('text-teal-200','text-hero-accent').replaceAll('text-orange-200','text-hero-accent'));}
// Position absolute form adornments and the hero decoration by direction.
for(const p of ['app/login/page.tsx','app/register/page.tsx','app/admin/page.tsx','components/ui/sheet.tsx','app/page.tsx','app/layout.tsx'])edit(p,s=>s.replace(/\bright-(3|4)\b/g,'end-$1').replace(/\bleft-(2|3)\b/g,'start-$1').replace('-right-16','-end-16'));
